apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: longhorn-home-ff1-dev
  namespace: longhorn-system
spec:
  secretName: longhorn-dashboard-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  dnsNames:
    - longhorn.home.ff1.dev
