apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: grafana-home-ff1-dev
  namespace: monitoring
spec:
  secretName: grafana-dashboard-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  dnsNames:
    - grafana.home.ff1.dev
